
/* === AutoGenerated Content === */

function InitScheduleGrid()
{
	for (var i = 0; i < (23-7)*2; i++)
	{
		$(".grid-container").append("<div class='grid-item time' style='grid-row: " + (i*2+2) + "/ span 2;'>" + ((Math.floor(i/2)+6)%12+1) + ":" + (i%2 ? "30" : "00") + ((i<=9?"am":"pm")) + "</div>");
		for (var j = 0; j < 7; j++)
		{
			$(".grid-container").append("<div class='grid-item space' style='grid-row:" + (i*2+2) + "/ span 2;'></div>");
		}
	}
}

/* === Dynamic Element Handlers === */

var CourseTemplate = $(".CourseTemplate")[0];
function AddCourse()
{
	//generate new element
	var newElem = CourseTemplate.cloneNode(true);
	newElem.className = "Course";
	
	//bind buttons
	$(newElem).find(".sectionAdd").click(AddSection);
	$(newElem).find(".accordionButton").click(AccordionClick);
	$(newElem).find(".courseRemove").click(RemoveCourse);
	
	//add initial children
	AddSectionLoc($(newElem).find(".SectionListContainer"));
	
	//append to list
	$(".CourseListContainer").append(newElem);
}

function RemoveCourse()
{
	var list = $(this).closest(".CourseListContainer");
	$(this).closest(".Course").remove();
	if (list.children().length<=0)
	{
		AddCourse();
	}
}

var SectionTemplate = $(".SectionTemplate")[0];
function AddSection()
{
	AddSectionLoc($(this).siblings(".SectionListContainer"));
}
function AddSectionLoc(location)
{
	//generate new element
	var newElem = SectionTemplate.cloneNode(true);
	newElem.className = "Section";
	
	//bind buttons
	$(newElem).find(".timeSlotAdd").click(AddTimeSlot);
	$(newElem).find(".accordionButton").click(AccordionClick);
	$(newElem).find(".sectionRemove").click(RemoveSection);
	
	//add initial children
	AddTimeSlotLoc($(newElem).find(".TimeSlotListContainer"));
	
	//append to list
	location.append(newElem);
}

function RemoveSection()
{
	var list = $(this).closest(".SectionListContainer");
	$(this).closest(".Section").remove();
	if (list.children().length <= 0)
	{
		AddSectionLoc(list);
	}
}

var TimeSlotTemplate = $(".TimeSlotTemplate")[0];
function AddTimeSlot()
{
	AddTimeSlotLoc($(this).siblings(".TimeSlotListContainer"));
}
function AddTimeSlotLoc(location)
{
	//generate new element
	var newElem = TimeSlotTemplate.cloneNode(true);
	newElem.className = "TimeSlot";
	
	//bind buttons
	$(newElem).find(".timeSlotRemove").click(RemoveTimeSlot);
	$(newElem).find("button.day-button").click(DayButtonClick);
	
	//append to list
	location.append(newElem);
}

function RemoveTimeSlot()
{
	var list = $(this).closest(".TimeSlotListContainer");
	$(this).closest(".TimeSlot").remove();
	if (list.children().length <= 0)
	{
		AddTimeSlotLoc(list);
	}
}

/* === End Dynamic Element Handlers === */


/* === Accordian Handling begins here === */

$(".accordionButton").click(AccordionClick);

function AccordionClick()
{
	this.parentElement.nextElementSibling.classList.toggle("active");
	if (this.parentElement.nextElementSibling.classList.contains("active"))
	{
		this.firstChild.classList.remove("fa-arrow-alt-circle-right")
		this.firstChild.classList.add("fa-arrow-alt-circle-down");
	}
	else
	{
		this.firstChild.classList.remove("fa-arrow-alt-circle-down")
		this.firstChild.classList.add("fa-arrow-alt-circle-right");
	}
}


/* === Accordian Handling ends here === */


/* === Button Handlers === */

/* Course */

$(".courseAdd").click(AddCourse);

/* Section */

//$(".sectionAdd").click(AddSection);

/* TimeTable */

//$(".timeslotAdd").click(AddTimeSlot);


//$("button.day-button").click(DayButtonClick);

function DayButtonClick()
{
	this.classList.toggle("active");
}

/* Schedule */

function GenerateSchedule()
{
	
}

function DrawSchedule()
{
	
}


/* === End Button Handlers === */


/* === Init Items === */

AddCourse();

InitScheduleGrid();

/* === End Init Items === */
