
/* === AutoGenerated Content === */

InitScheduleGrid();

function InitScheduleGrid()
{
	for (var i = 0; i < (23-7)*2; i++)
	{
		$(".grid-container").append("<div class='grid-item time' style='grid-row: " + (i*2+2) + "/ span 2;'>" + ((Math.floor(i/2)+6)%12+1) + ":" + (i%2 ? "30" : "00") + ((i<=9?"am":"pm")) + "</div>");
		for (var j = 0; j < 7; j++)
		{
			$(".grid-container").append("<div class='grid-item space' style='grid-row:" + (i*2+2) + "/ span 2;'></div>");
		}
	}
}


/* === Dynamic Element Handlers === */

function AddCourse()
{
	//Copy template and append to end of dynamic list
	//Bind Buttons
	//add initial empty section
}

function DeleteCourse()
{
	//if last course is being deleted, add initial empty course
}

function AddSection()
{
	//Copy template and append to end of dynamic list
	//Bind Buttons
	//add initial empty timeslot
}

function DeleteSection()
{
	//if last course is being deleted, add initial empty section
}

function AddTimeSlot()
{
	//Copy template and append to end of dynamic list
	//Bind Buttons
}

function DeleteTimeSlot()
{
	//if last course is being deleted, add initial empty timeslot
}

/* === End Dynamic Element Handlers === */


/* === Accordian Handling begins here === */

$(".accordionButton").click(AccordionClick);

function AccordionClick()
{
	this.parentElement.nextElementSibling.classList.toggle("active");
}


/* === Accordian Handling ends here === */


/* === Button Handlers === */


/* Course */

/* Section */

/* TimeTable */

$("button.day-button").click(DayButtonClick);

function DayButtonClick()
{
	this.classList.toggle("active");
}

/* Schedule */

function GenerateSchedule()
{
	
}

function DrawSchedule()
{
	
}


/* === End Button Handlers === */



